### ISSUE TITLE
Edge processing

### ISSUE THREAD

**Issue by stakach** [place-technology/roadmap#12]
**Is your feature request related to a problem? Please describe.**

When a client has networks that they don't want egress to the internet we can have drivers running on cisco switches.
Cisco whitelists traffic from the core instance on the switch to the PlaceOS platform.

This means nothing on the internet can directly connect to the security system or HVAC for example.

**Describe the solution you'd like**

<img width="571" alt="image" src="https://user-images.githubusercontent.com/368013/93545200-3442cd00-f9a3-11ea-86e6-60bfb93df353.png">

Effectively a way of creating edges that modules run in.
The default being how the system runs currently - distribution of work to local core instances
Then we have an edge gateway service, where cores connect in (authenticated) and register themselves as an edge group (could be multiple edge cores in a single edge group)
The edge gateway service then does:
* the job of etcd - informing the connected cores of the other connections from the same edge group
* rethinkdb - streaming the driver and module information relevant to that edge group
* redis state proxy - taking state on the edge cores and pushing it into the cloud redis cluster
* proxying exec requests down to the edge group (sending the request directly to the core instance running the driver)

To simplify things, only device drivers can run on the edge (no logic) - this keeps the drivers isolated as we don't want to run redis on the edge, redis behaviours can easily be emulated for a self contained driver.

**Comment by stakach** [comment]
I was thinking that in backoffice we create "edge zones"

* this generates an secret key that can be used by that edge cores to connect to the Edge Connect service
* when creating a module, you can optionally allocate the module to an Edge Connect zone
* these modules are then distributed between the Edge Cores using consistent hashing just like Cloud Cores

**Comment by jeremy-west** [comment]
Created in Forecast: https://app.forecast.it/project/P-67/scoping

**Comment by w-le** [comment]
More information:
- https://www.cisco.com/c/dam/en/us/products/collateral/switches/catalyst-9300-series-switches/white-paper-c87-742415.pdf
- https://developer.cisco.com/docs/app-hosting/
